### ISSUE TITLE
SBT_URL does not point to sbt-launch.jar anymore (HTTP 404) --> Scala buildpack fails

### ISSUE THREAD

**Issue by stefan-schlott-cah** [cloudControl/buildpack-scala#3]
Currently we have the issue that every application based on the Scala buildpack fails because sbt-launch.jar cannot be downloaded and therefore the build tool is just not available.

The simple reason is that the variable SBT_URL in the file bin/compile just does not point to an active URL.

In an App push/compile process it looks like that:

`-----> Downloading SBT... !     Failed to download sbt-launch.jar`

The whole seems to be related to an URL change by the SBT project, e.g. a reason why travis-ci had issues as well --> https://github.com/travis-ci/travis-ci/issues/4527

The travis-ci issue should also contain the now correct URL for sbt-launch.jar. 

The according line in bin/compile is referenced here: https://github.com/cloudControl/buildpack-scala/commit/e7334a1f3e408129d8febad26d4e2ac30707a31e

**Comment by pst** [comment]
This seems to be work in progress https://github.com/cloudControl/buildpack-scala/commit/98035f4a9e0ce3f36d6d5eaf9ea57476ed6788c9
